name: Deploy to Firebase Hosting (2 Sites)

on:
  push:
    branches:
      - main

jobs:
  deploy-kalharaj:
    name: Deploy to kalharaj.web.app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KALHARAJ }}
          projectId: kalharaj
          channelId: live

  deploy-kalharajayathissa:
    name: Deploy to kalharajayathissa.web.app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KALHARAJAYATHISSA }}
          projectId: kalharajayathissa
          channelId: live
